patch:
  schema_list:
    - {schema: wubi86}
  ascii_composer/switch_key/Shift_L: commit_code
  ascii_composer/switch_key/Shift_R: commit_code
  "switcher/hotkeys":  # about key name refer to <https://github.com/rime/librime/blob/master/include/X11/keysymdef.h>, remove XK_
    - "Control+F12"  # Ctrl+\